% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  11pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Lab},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Lab}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\section{Uppgift 1. Enkel linjär
regression}\label{uppgift-1.-enkel-linjuxe4r-regression}

\subsection{(a) Simulera data och anpassa
modellen}\label{a-simulera-data-och-anpassa-modellen}

Vi genererar heltal \(x=1,\dots,20\) och simulerar
\(y=\beta_0+\beta_1 x+\varepsilon\) med \(\beta_0=2\), \(\beta_1=1\),
\(\varepsilon\sim\mathcal{N}(0,\sigma^2)\), \(\sigma=3\). Dessa värden
ger \(R^2\) mellan 70--90\%.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)                 }\CommentTok{\# reproducerbart en gång }
\NormalTok{x }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\NormalTok{beta0 }\OtherTok{\textless{}{-}} \DecValTok{2}
\NormalTok{beta1 }\OtherTok{\textless{}{-}} \DecValTok{1}
\NormalTok{sigma }\OtherTok{\textless{}{-}} \DecValTok{3}
\NormalTok{eps }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\FunctionTok{length}\NormalTok{(x), }\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =}\NormalTok{ sigma)}
\NormalTok{y }\OtherTok{\textless{}{-}}\NormalTok{ beta0 }\SpecialCharTok{+}\NormalTok{ beta1}\SpecialCharTok{*}\NormalTok{x }\SpecialCharTok{+}\NormalTok{ eps}

\NormalTok{fit }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x)}
\FunctionTok{summary}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.964 -1.808 -0.113  1.558  5.201 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   2.9303     1.3860   2.114   0.0487 *  
## x             0.9519     0.1157   8.227 1.64e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.984 on 18 degrees of freedom
## Multiple R-squared:  0.7899, Adjusted R-squared:  0.7783 
## F-statistic: 67.68 on 1 and 18 DF,  p-value: 1.642e-07
\end{verbatim}

\subsection{\texorpdfstring{(b) 95\% konfidensintervall för
\(\beta_0,\beta_1\)}{(b) 95\% konfidensintervall för \textbackslash beta\_0,\textbackslash beta\_1}}\label{b-95-konfidensintervall-fuxf6r-beta_0beta_1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(ci }\OtherTok{\textless{}{-}} \FunctionTok{confint}\NormalTok{(fit, }\AttributeTok{level =} \FloatTok{0.95}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  2.5 %   97.5 %
## (Intercept) 0.01840497 5.842150
## x           0.70878766 1.194945
\end{verbatim}

Ja, de finns i intervallen.

\subsection{(c) Grafisk diagnostik}\label{c-grafisk-diagnostik}

Sexp figurer: spridningsdiagram (utan linje), spridningsdiagram med
anpassad linje samt de 4 diagnostiska plottarna.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(x, y, }\AttributeTok{main =} \StringTok{"y mot x"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"x"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"y"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(x, y, }\AttributeTok{main =} \StringTok{"y mot x med anpassning"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"x"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"y"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(fit, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(fit, }\AttributeTok{which =} \DecValTok{1}\NormalTok{)  }\CommentTok{\# Residualer mot anpassade värden (Residuals vs Fitted)}
\FunctionTok{plot}\NormalTok{(fit, }\AttributeTok{which =} \DecValTok{2}\NormalTok{)  }\CommentTok{\# Normal Q{-}Q}
\FunctionTok{plot}\NormalTok{(fit, }\AttributeTok{which =} \DecValTok{3}\NormalTok{)  }\CommentTok{\# Scale{-}Location}
\FunctionTok{plot}\NormalTok{(fit, }\AttributeTok{which =} \DecValTok{5}\NormalTok{)  }\CommentTok{\# Residualer mot hävstång (Cook\textquotesingle{}s konturer)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(op)}
\end{Highlighting}
\end{Shaded}

\textbf{Vad plottarna visar:}

\begin{itemize}
\tightlist
\item
  \textbf{Spridningsdiagrammen}: linjärt samband tydligt.
\item
  \textbf{Residualer mot anpassade värden}: kontrollerar linearitet \&
  konstant varians (bör vara slumpmoln).
\item
  \textbf{Normal Q--Q}: kontrollerar ungefärlig normalitet (punkter nära
  linjen).
\item
  \textbf{Scale--Location}: kontrollerar homogen varians (platt band).
\item
  \textbf{Residualer mot hävstång (Cook's distans)}: flaggar hög
  hävstång/inflytande.
\end{itemize}

Modellen passar väl till datan.

\subsection{(d) Upprepade simuleringar för att se diagnostikens
variation}\label{d-upprepade-simuleringar-fuxf6r-att-se-diagnostikens-variation}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{seed }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(seed)}
\CommentTok{\# Simulera en ny datamängd vid varje körning och rita om diagnostiken}
\NormalTok{x }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\NormalTok{beta0 }\OtherTok{\textless{}{-}} \DecValTok{2}\NormalTok{; beta1 }\OtherTok{\textless{}{-}} \DecValTok{1}\NormalTok{; sigma }\OtherTok{\textless{}{-}} \DecValTok{3}
\NormalTok{y }\OtherTok{\textless{}{-}}\NormalTok{ beta0 }\SpecialCharTok{+}\NormalTok{ beta1}\SpecialCharTok{*}\NormalTok{x }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(}\FunctionTok{length}\NormalTok{(x), }\DecValTok{0}\NormalTok{, sigma)}
\NormalTok{fit }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x)}

\NormalTok{op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(x, y, }\AttributeTok{main =} \StringTok{"y mot x"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"x"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"y"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(x, y, }\AttributeTok{main =} \StringTok{"y mot x med anpassning"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"x"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"y"}\NormalTok{); }\FunctionTok{abline}\NormalTok{(fit, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(fit, }\AttributeTok{which =} \DecValTok{1}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit, }\AttributeTok{which =} \DecValTok{2}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit, }\AttributeTok{which =} \DecValTok{3}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit, }\AttributeTok{which =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(op)}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Även när modellen stämmer kan residualmönster, QQ-svansar och
Scale--Location-kurvan variera på grund av slump; plott av
hävstång/Cook's är oftast mest stabil såvida inte ett extremt drag
uppstår. Små mönster ska tolkas med försiktighet.

\subsection{\texorpdfstring{(e) Bryt mot antagandet om homogen varians
(variansen ökar med
\(x\))}{(e) Bryt mot antagandet om homogen varians (variansen ökar med x)}}\label{e-bryt-mot-antagandet-om-homogen-varians-variansen-uxf6kar-med-x}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{x }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\NormalTok{beta0 }\OtherTok{\textless{}{-}} \DecValTok{2}\NormalTok{; beta1 }\OtherTok{\textless{}{-}} \DecValTok{1}\NormalTok{; sigma }\OtherTok{\textless{}{-}} \FloatTok{0.8}
\NormalTok{y\_het }\OtherTok{\textless{}{-}}\NormalTok{ beta0 }\SpecialCharTok{+}\NormalTok{ beta1}\SpecialCharTok{*}\NormalTok{x }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(}\FunctionTok{length}\NormalTok{(x), }\DecValTok{0}\NormalTok{, sigma }\SpecialCharTok{*}\NormalTok{ (x}\SpecialCharTok{/}\FunctionTok{mean}\NormalTok{(x)))}
\NormalTok{fit\_het }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y\_het }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x)}

\NormalTok{op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(x, y\_het, }\AttributeTok{main =} \StringTok{"Heteroskedastisk y mot x"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(x, y\_het, }\AttributeTok{main =} \StringTok{"Med anpassning"}\NormalTok{); }\FunctionTok{abline}\NormalTok{(fit\_het, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(fit\_het, }\AttributeTok{which =} \DecValTok{1}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit\_het, }\AttributeTok{which =} \DecValTok{2}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit\_het, }\AttributeTok{which =} \DecValTok{3}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit\_het, }\AttributeTok{which =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(op)}
\end{Highlighting}
\end{Shaded}

\textbf{Tolkning (e):}

\begin{itemize}
\tightlist
\item
  Spridningsdiagrammen visar ett tydligt linjärt samband men
  \textbf{ökande spridning när x ökar}.
\item
  \textbf{Residuals vs Fitted:} trattform -- residualernas varians växer
  med anpassade värden ⇒ tydlig \textbf{heteroskedasticitet}.
\item
  \textbf{Scale--Location:} stigande kurva bekräftar
  \textbf{icke-konstant varians}.
\item
  \textbf{Q--Q:} punkter nära linjen ⇒ normalitetsantagandet verkar OK.
\item
  \textbf{Residuals vs Leverage:} inga uppenbart inflytelserika
  observationer (Cook's långt ifrån gränser).
\end{itemize}

\subsection{(f) Bryt mot linearitetsantagandet (sann kvadratisk
term)}\label{f-bryt-mot-linearitetsantagandet-sann-kvadratisk-term}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{x }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\NormalTok{beta0 }\OtherTok{\textless{}{-}} \DecValTok{2}\NormalTok{; beta1 }\OtherTok{\textless{}{-}} \FloatTok{0.2}\NormalTok{; beta2 }\OtherTok{\textless{}{-}} \FloatTok{0.08}\NormalTok{; sigma }\OtherTok{\textless{}{-}} \FloatTok{1.5}
\NormalTok{y\_nl }\OtherTok{\textless{}{-}}\NormalTok{ beta0 }\SpecialCharTok{+}\NormalTok{ beta1}\SpecialCharTok{*}\NormalTok{x }\SpecialCharTok{+}\NormalTok{ beta2}\SpecialCharTok{*}\NormalTok{x}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(}\FunctionTok{length}\NormalTok{(x), }\DecValTok{0}\NormalTok{, sigma)}
\NormalTok{fit\_lin }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y\_nl }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x)      }\CommentTok{\# (fel)anpassa en linjär modell}

\NormalTok{op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(x, y\_nl, }\AttributeTok{main =} \StringTok{"Icke{-}linjär y mot x"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(x, y\_nl, }\AttributeTok{main =} \StringTok{"Linjär anpassning över icke{-}linjär"}\NormalTok{); }\FunctionTok{abline}\NormalTok{(fit\_lin, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(fit\_lin, }\AttributeTok{which =} \DecValTok{1}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit\_lin, }\AttributeTok{which =} \DecValTok{2}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit\_lin, }\AttributeTok{which =} \DecValTok{3}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit\_lin, }\AttributeTok{which =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(op)}
\end{Highlighting}
\end{Shaded}

\textbf{Tolkning (f):}

\begin{itemize}
\tightlist
\item
  Spridningsdiagrammen visar tydlig \textbf{krökning (kvadratisk trend)}
  -- en linjär modell är fel
\item
  \textbf{Residuals vs Fitted:} markerad U-form ⇒ stark
  \textbf{icke-linearitet}.
\item
  \textbf{Scale--Location:} ingen tydlig trattform ⇒ variansen verkar
  ungefär konstant.
\item
  \textbf{Q--Q:} nära linjen ⇒ residualerna är ungefär \textbf{normala}.
\item
  \textbf{Residuals vs Leverage:} ytterpunkter har hög
  \textbf{hävstång}, viss men inte extrem påverkan (Cook's inte
  passerad).
\end{itemize}

\subsection{(g) Avvikare: inflytelserik vs
icke-inflytelserik}\label{g-avvikare-inflytelserik-vs-icke-inflytelserik}

Utgå från en ren linjär modell och stör en observation på två sätt.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{x }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\NormalTok{beta0 }\OtherTok{\textless{}{-}} \DecValTok{2}\NormalTok{; beta1 }\OtherTok{\textless{}{-}} \DecValTok{1}\NormalTok{; sigma }\OtherTok{\textless{}{-}} \DecValTok{2}
\NormalTok{y\_base }\OtherTok{\textless{}{-}}\NormalTok{ beta0 }\SpecialCharTok{+}\NormalTok{ beta1}\SpecialCharTok{*}\NormalTok{x }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(}\FunctionTok{length}\NormalTok{(x), }\DecValTok{0}\NormalTok{, sigma)}

\DocumentationTok{\#\# Fall 1: Icke{-}inflytelserik y{-}avvikare vid genomsnittlig hävstång}
\NormalTok{x1 }\OtherTok{\textless{}{-}}\NormalTok{ x}
\NormalTok{y1 }\OtherTok{\textless{}{-}}\NormalTok{ y\_base}
\NormalTok{y1[}\DecValTok{10}\NormalTok{] }\OtherTok{\textless{}{-}}\NormalTok{ y1[}\DecValTok{10}\NormalTok{] }\SpecialCharTok{+} \DecValTok{12}     \CommentTok{\# stort residual vid måttligt x}
\NormalTok{fit1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y1 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x1)}

\DocumentationTok{\#\# Fall 2: Inflytelserik hög{-}hävstångs{-}avvikare (extremt x)}
\NormalTok{x2 }\OtherTok{\textless{}{-}}\NormalTok{ x}
\NormalTok{x2[}\DecValTok{20}\NormalTok{] }\OtherTok{\textless{}{-}} \DecValTok{40}              \CommentTok{\# långt utanför designintervallet}
\NormalTok{y2 }\OtherTok{\textless{}{-}}\NormalTok{ y\_base}
\NormalTok{y2[}\DecValTok{20}\NormalTok{] }\OtherTok{\textless{}{-}}\NormalTok{ beta0 }\SpecialCharTok{+}\NormalTok{ beta1}\SpecialCharTok{*}\NormalTok{x2[}\DecValTok{20}\NormalTok{] }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{6}\NormalTok{) }\SpecialCharTok{+} \DecValTok{10}  \CommentTok{\# även förskjuten i y}
\NormalTok{fit2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y2 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x2)}

\CommentTok{\# Plottar: vardera i ett 2x3{-}upplägg}
\NormalTok{op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(x1, y1, }\AttributeTok{main =} \StringTok{"Icke{-}inflytelserik avvikare"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(x1, y1, }\AttributeTok{main =} \StringTok{"Med anpassning"}\NormalTok{); }\FunctionTok{abline}\NormalTok{(fit1, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(fit1, }\AttributeTok{which =} \DecValTok{1}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit1, }\AttributeTok{which =} \DecValTok{2}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit1, }\AttributeTok{which =} \DecValTok{3}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit1, }\AttributeTok{which =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(op)}

\NormalTok{op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(x2, y2, }\AttributeTok{main =} \StringTok{"Inflytelserik avvikare"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(x2, y2, }\AttributeTok{main =} \StringTok{"Med anpassning"}\NormalTok{); }\FunctionTok{abline}\NormalTok{(fit2, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(fit2, }\AttributeTok{which =} \DecValTok{1}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit2, }\AttributeTok{which =} \DecValTok{2}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit2, }\AttributeTok{which =} \DecValTok{3}\NormalTok{); }\FunctionTok{plot}\NormalTok{(fit2, }\AttributeTok{which =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-7-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(op)}
\end{Highlighting}
\end{Shaded}

\textbf{Tolkning (g):}

\begin{itemize}
\item
  \textbf{Icke-inflytelserik outlier (fall 1):} I spridningsdiagrammet
  syns en tydlig y-avvikare kring medel-x. Den ger \textbf{stort
  residual} (Residuals vs Fitted) och avviker i \textbf{Q--Q} men har
  \textbf{låg hävstång}; i \textbf{Residuals vs Leverage} ligger punkten
  långt till vänster och \textbf{under Cook's}-konturer ⇒ liten påverkan
  på linjen.
\item
  \textbf{Inflytelserik outlier (fall 2):} Punkt med \textbf{extremt x}
  drar regressionslinjen (synligt i ``Med anpassning''). I
  \textbf{Residuals vs Leverage} har den \textbf{hög hävstång} och
  ligger nära/över \textbf{Cook's}-konturer ⇒ \textbf{inflytelserik}.
  Residualen är inte nödvändigtvis störst i ``Residuals vs Fitted'', men
  kombinationen av stort leverage + Cook's gör den tydligt påverkande.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Uppgift 2. Multipel linjär regression ---
Cigarettdata}\label{uppgift-2.-multipel-linjuxe4r-regression-cigarettdata}

\subsection{(a) Enkla regressioner för prediktion av
CO}\label{a-enkla-regressioner-fuxf6r-prediktion-av-co}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Läs in data {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{cig }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"cigarette.csv"}\NormalTok{, }\AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Snabb översikt}
\FunctionTok{str}\NormalTok{(cig)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    25 obs. of  5 variables:
##  $ brand : chr  "Alpine" "Benson&Hedges" "BullDurham" "CamelLights" ...
##  $ tar   : num  14.1 16 29.8 8 4.1 15 8.8 12.4 16.6 14.9 ...
##  $ nico  : num  0.86 1.06 2.03 0.67 0.4 1.04 0.76 0.95 1.12 1.02 ...
##  $ weight: num  0.985 1.094 1.165 0.928 0.946 ...
##  $ CO    : num  13.6 16.6 23.5 10.2 5.4 15 9 12.3 16.3 15.4 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Spridningsdiagram med enkla linjära anpassningar}
\NormalTok{op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(cig}\SpecialCharTok{$}\NormalTok{tar, cig}\SpecialCharTok{$}\NormalTok{CO, }\AttributeTok{xlab =} \StringTok{"Tjära (mg)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"CO (mg)"}\NormalTok{, }\AttributeTok{main =} \StringTok{"CO \textasciitilde{} tar"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\FunctionTok{lm}\NormalTok{(CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tar, }\AttributeTok{data =}\NormalTok{ cig), }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(cig}\SpecialCharTok{$}\NormalTok{nico, cig}\SpecialCharTok{$}\NormalTok{CO, }\AttributeTok{xlab =} \StringTok{"Nikotin (mg)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"CO (mg)"}\NormalTok{, }\AttributeTok{main =} \StringTok{"CO \textasciitilde{} nico"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\FunctionTok{lm}\NormalTok{(CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nico, }\AttributeTok{data =}\NormalTok{ cig), }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(cig}\SpecialCharTok{$}\NormalTok{weight, cig}\SpecialCharTok{$}\NormalTok{CO, }\AttributeTok{xlab =} \StringTok{"Vikt (g)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"CO (mg)"}\NormalTok{, }\AttributeTok{main =} \StringTok{"CO \textasciitilde{} weight"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\FunctionTok{lm}\NormalTok{(CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ weight, }\AttributeTok{data =}\NormalTok{ cig), }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(op)}

\CommentTok{\# Anpassa enkla modeller och summera}
\NormalTok{m\_tar    }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tar,    }\AttributeTok{data =}\NormalTok{ cig)}
\NormalTok{m\_nico   }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nico,   }\AttributeTok{data =}\NormalTok{ cig)}
\NormalTok{m\_weight }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ weight, }\AttributeTok{data =}\NormalTok{ cig)}

\FunctionTok{summary}\NormalTok{(m\_tar)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = CO ~ tar, data = cig)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.1124 -0.7167 -0.3754  1.0091  2.5450 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  2.74328    0.67521   4.063 0.000481 ***
## tar          0.80098    0.05032  15.918 6.55e-14 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.397 on 23 degrees of freedom
## Multiple R-squared:  0.9168, Adjusted R-squared:  0.9132 
## F-statistic: 253.4 on 1 and 23 DF,  p-value: 6.552e-14
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(m\_nico)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = CO ~ nico, data = cig)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.3273 -1.2228  0.2304  1.2700  3.9357 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   1.6647     0.9936   1.675    0.107    
## nico         12.3954     1.0542  11.759 3.31e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.828 on 23 degrees of freedom
## Multiple R-squared:  0.8574, Adjusted R-squared:  0.8512 
## F-statistic: 138.3 on 1 and 23 DF,  p-value: 3.312e-11
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(m\_weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = CO ~ weight, data = cig)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -6.524 -2.533  0.622  2.842  7.268 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)  
## (Intercept)  -11.795      9.722  -1.213   0.2373  
## weight        25.068      9.980   2.512   0.0195 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.289 on 23 degrees of freedom
## Multiple R-squared:  0.2153, Adjusted R-squared:  0.1811 
## F-statistic: 6.309 on 1 and 23 DF,  p-value: 0.01948
\end{verbatim}

\textbf{Tolkning 2(a):}

\begin{itemize}
\tightlist
\item
  \textbf{CO \textasciitilde{} tar:} Mycket starkt linjärt samband.
  \(R^2 \approx 0.92\), lutning ≈ \textbf{0.81 mg CO per mg tjära} (p ≪
  0.001). Bra för prediktion.
\item
  \textbf{CO \textasciitilde{} nico:} Också starkt linjärt samband.
  \(R^2 \approx 0.86\), lutning ≈ \textbf{12.4 mg CO per mg nikotin} (p
  ≪ 0.001). Bra för prediktion.
\item
  \textbf{CO \textasciitilde{} weight:} Svagt samband.
  \(R^2 \approx 0.22\), lutning signifikant men osäker praktiskt
  (p≈0.02); spridningen stor ⇒ \textbf{svag prediktor}.
\end{itemize}

Enkel linjär regression fungerar \textbf{väl} för att prediktera CO med
\textbf{tjära} eller \textbf{nikotin} var för sig, men \textbf{dåligt}
med \textbf{vikt} som ensam förklarande variabel.

\subsection{(b) Multipel regression med alla tre
prediktorer}\label{b-multipel-regression-med-alla-tre-prediktorer}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m\_all }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tar }\SpecialCharTok{+}\NormalTok{ nico }\SpecialCharTok{+}\NormalTok{ weight, }\AttributeTok{data =}\NormalTok{ cig)}
\FunctionTok{summary}\NormalTok{(m\_all)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = CO ~ tar + nico + weight, data = cig)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.89261 -0.78269  0.00428  0.92891  2.45082 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   3.2022     3.4618   0.925 0.365464    
## tar           0.9626     0.2422   3.974 0.000692 ***
## nico         -2.6317     3.9006  -0.675 0.507234    
## weight       -0.1305     3.8853  -0.034 0.973527    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.446 on 21 degrees of freedom
## Multiple R-squared:  0.9186, Adjusted R-squared:  0.907 
## F-statistic: 78.98 on 3 and 21 DF,  p-value: 1.329e-11
\end{verbatim}

\textbf{Tolkning 2(b):}

\begin{itemize}
\tightlist
\item
  I den multipla modellen är \textbf{tjära} positiv och
  \textbf{signifikant} (β≈0.96, p≈7e-4).
\item
  \textbf{Nikotin} blir \textbf{icke-signifikant} och byter tecken
  (β≈−2.6, p≈0.51) -- typiskt tecken på \textbf{kollinearitet} med
  tjära.
\item
  \textbf{Vikt} är också \textbf{icke-signifikant} (p≈0.97).
\item
  \(R^2=0.919\) är bara marginellt högre än för CO\textasciitilde tar,
  men \textbf{justerat \(R^2=0.907\) är lägre} än för
  CO\textasciitilde tar (≈0.913), och residual-SE är större (1.45 vs
  1.40).
\end{itemize}

Att lägga till nikotin och vikt ger ingen praktisk förbättring;
\textbf{CO\textasciitilde tar} räcker bäst av de provade modellerna.

\subsection{(c) Parvisa plottar för att förklara
(b)}\label{c-parvisa-plottar-fuxf6r-att-fuxf6rklara-b}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pairs}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ CO }\SpecialCharTok{+}\NormalTok{ tar }\SpecialCharTok{+}\NormalTok{ nico }\SpecialCharTok{+}\NormalTok{ weight, }\AttributeTok{data =}\NormalTok{ cig)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-10-1.pdf}

\textbf{Tolkning 2(c):}

\begin{itemize}
\tightlist
\item
  \textbf{CO--tar} och \textbf{CO--nico}: tydliga, starkt positiva
  linjära samband → båda förklarar CO bra var för sig.
\item
  \textbf{CO--weight}: svagt samband och stor spridning → dålig ensam
  prediktor.
\item
  \textbf{tar--nico}: mycket starkt positiv korrelation →
  \textbf{kollinearitet}. Det förklarar att nikotin blir
  icke-signifikant och kan byta tecken i den multipla modellen i (b) när
  tjära redan finns med.
\item
  \textbf{weight} mot tar/nico: inga starka samband → liten extra
  information att tillföra modellen.
\end{itemize}

\subsection{(d) Residualdiagnostik för den multipla
regressionen}\label{d-residualdiagnostik-fuxf6r-den-multipla-regressionen}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(m\_all)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(op)}
\end{Highlighting}
\end{Shaded}

\textbf{Tolkning 2(d):}

\begin{itemize}
\tightlist
\item
  \textbf{Residuals vs Fitted:} svag krökning och systematik; inte helt
  linjärt.
\item
  \textbf{Q--Q:} nära linjen men några svansavvikelser (t.ex. 17, 25) ⇒
  något tunga svansar.
\item
  \textbf{Scale--Location:} ökande trend → tecken på
  \textbf{heteroskedasticitet} (större spridning vid höga förklarade
  värden).
\item
  \textbf{Residuals vs Leverage:} observation \textbf{30} har
  \textbf{hög hävstång} och \textbf{stort residual} (nära/över Cook's) ⇒
  \textbf{inflytelserik}.
\end{itemize}

Den multipla linjära modellen är delvis rimlig men diagnosen visar
möjlig icke-linearitet, icke-konstant varians och en inflytelserik punkt
(nr 30) som bör utredas/hanteras.

\subsection{(e) Identifiera och uteslut den tvivelaktiga observationen,
anpassa
om}\label{e-identifiera-och-uteslut-den-tvivelaktiga-observationen-anpassa-om}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Influensdiagnostik}
\NormalTok{infl }\OtherTok{\textless{}{-}} \FunctionTok{influence.measures}\NormalTok{(m\_all)}
\NormalTok{cook }\OtherTok{\textless{}{-}} \FunctionTok{cooks.distance}\NormalTok{(m\_all)}
\NormalTok{lev  }\OtherTok{\textless{}{-}} \FunctionTok{hatvalues}\NormalTok{(m\_all)}

\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(cig)}
\NormalTok{thr }\OtherTok{\textless{}{-}} \DecValTok{4}\SpecialCharTok{/}\NormalTok{n                            }\CommentTok{\# ett vanligt riktmärke för att flagga Cook\textquotesingle{}s D}
\NormalTok{flag }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(cook }\SpecialCharTok{\textgreater{}}\NormalTok{ thr)}
\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{brand =}\NormalTok{ cig}\SpecialCharTok{$}\NormalTok{brand[flag], }\AttributeTok{cooksD =}\NormalTok{ cook[flag], }\AttributeTok{leverage =}\NormalTok{ lev[flag])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            brand    cooksD  leverage
## 3     BullDurham 2.0937714 0.5074842
## 14   MultiFilter 0.1715736 0.2534280
## 16           Now 0.3463355 0.2933370
## 17       OldGold 0.2096934 0.1998589
## 25 WinstonLights 0.2712300 0.2261056
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ta bort den mest tvivelaktiga och anpassa om}
\NormalTok{idx\_q }\OtherTok{\textless{}{-}}\NormalTok{ flag[}\FunctionTok{which.max}\NormalTok{(cook[flag])]}
\NormalTok{cig\_red }\OtherTok{\textless{}{-}}\NormalTok{ cig[}\SpecialCharTok{{-}}\NormalTok{idx\_q, ]}

\NormalTok{m\_all\_red }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tar }\SpecialCharTok{+}\NormalTok{ nico }\SpecialCharTok{+}\NormalTok{ weight, }\AttributeTok{data =}\NormalTok{ cig\_red)}
\FunctionTok{summary}\NormalTok{(m\_all\_red)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = CO ~ tar + nico + weight, data = cig_red)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1083 -0.8046 -0.1199  1.0095  2.0501 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  -0.5517     2.9713  -0.186 0.854569    
## tar           0.8876     0.1955   4.540 0.000199 ***
## nico          0.5185     3.2523   0.159 0.874941    
## weight        2.0793     3.1784   0.654 0.520431    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.16 on 20 degrees of freedom
## Multiple R-squared:  0.935,  Adjusted R-squared:  0.9252 
## F-statistic: 95.86 on 3 and 20 DF,  p-value: 4.85e-12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Jämför koefficienter, p{-}värden, R\^{}2}
\NormalTok{coef\_comparison }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}
  \AttributeTok{full =} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(m\_all))[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Estimate"}\NormalTok{, }\StringTok{"Pr(\textgreater{}|t|)"}\NormalTok{)],}
  \AttributeTok{reduced =} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(m\_all\_red))[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Estimate"}\NormalTok{, }\StringTok{"Pr(\textgreater{}|t|)"}\NormalTok{)]}
\NormalTok{)}
\NormalTok{coef\_comparison}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Estimate     Pr(>|t|)   Estimate     Pr(>|t|)
## (Intercept)  3.2021900 0.3654642718 -0.5516976 0.8545685010
## tar          0.9625739 0.0006920652  0.8875803 0.0001990908
## nico        -2.6316611 0.5072342597  0.5184696 0.8749410220
## weight      -0.1304819 0.9735267532  2.0793442 0.5204306639
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{c}\NormalTok{(}\AttributeTok{R2\_full =} \FunctionTok{summary}\NormalTok{(m\_all)}\SpecialCharTok{$}\NormalTok{r.squared,}
  \AttributeTok{AdjR2\_full =} \FunctionTok{summary}\NormalTok{(m\_all)}\SpecialCharTok{$}\NormalTok{adj.r.squared,}
  \AttributeTok{R2\_reduced =} \FunctionTok{summary}\NormalTok{(m\_all\_red)}\SpecialCharTok{$}\NormalTok{r.squared,}
  \AttributeTok{AdjR2\_reduced =} \FunctionTok{summary}\NormalTok{(m\_all\_red)}\SpecialCharTok{$}\NormalTok{adj.r.squared)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       R2_full    AdjR2_full    R2_reduced AdjR2_reduced 
##     0.9185893     0.9069593     0.9349753     0.9252216
\end{verbatim}

\textbf{Tolkning 2(e):}

\begin{itemize}
\item
  \textbf{Tvivelaktig observation:} \emph{BullDurham} (nr 3) -- hög
  Cook's D (\textasciitilde2.09) och hög hävstång (\textasciitilde0.51)
  ⇒ starkt inflytelserik.
\item
  \textbf{Efter att ta bort den:}

  \begin{itemize}
  \tightlist
  \item
    Endast \textbf{tjära} är fortsatt \textbf{signifikant} (β≈0.89,
    p≈2e-4).
  \item
    \textbf{Nikotin} blir positiv men \textbf{icke-signifikant};
    \textbf{vikt} fortsatt icke-signifikant.
  \item
    Modellens passform \textbf{förbättras}: \(R^2\) från 0.919 →
    \textbf{0.935}, justerat \(R^2\) från 0.907 → \textbf{0.925}, och
    residual-SE minskar (≈1.45 → \textbf{1.16}).
  \end{itemize}
\end{itemize}

\textbf{Hur presentera:} Redovisa resultaten \textbf{med och utan}
outlier. Slutsatsen är robust: CO förklaras främst av \textbf{tjära};
outlieren påverkade koefficienterna (framför allt tecknet för nikotin)
och försämrade passformen.

\subsection{\texorpdfstring{(f) Modellval för prediktion (justerat
\(R^2\) och
LOOCV-RMSEP)}{(f) Modellval för prediktion (justerat R\^{}2 och LOOCV-RMSEP)}}\label{f-modellval-fuxf6r-prediktion-justerat-r2-och-loocv-rmsep}

Vi jämför kandidater med justerat \(R^2\) och LOOCV-RMSEP. Vi överväger:

\begin{itemize}
\tightlist
\item
  tar; nico; weight (enskilda prediktorer)
\item
  tar+nico; tar+weight; nico+weight
\item
  tar+nico+weight (full)
\end{itemize}

Du kan beräkna med eller utan den tvivelaktiga observationen; motivera
ditt val. Nedan visar vi båda och väljer modellen med \textbf{lägst
RMSEP} (vid lika RMSEP bryter vi med högre justerat \(R^2\) och
parsimoni).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Hjälpare: LOOCV{-}RMSEP för en linjär modell specificerad med formel och data.frame}
\NormalTok{loocv\_rmsep }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(formula, data) \{}
\NormalTok{  n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(data)}
  \CommentTok{\# analytisk LOOCV med hatt{-}matris (gäller linjär minsta{-}kvadrat)}
\NormalTok{  X }\OtherTok{\textless{}{-}} \FunctionTok{model.matrix}\NormalTok{(formula, }\AttributeTok{data =}\NormalTok{ data)}
\NormalTok{  y }\OtherTok{\textless{}{-}} \FunctionTok{model.response}\NormalTok{(}\FunctionTok{model.frame}\NormalTok{(formula, }\AttributeTok{data =}\NormalTok{ data))}
\NormalTok{  hat }\OtherTok{\textless{}{-}}\NormalTok{ X }\SpecialCharTok{\%*\%} \FunctionTok{solve}\NormalTok{(}\FunctionTok{t}\NormalTok{(X) }\SpecialCharTok{\%*\%}\NormalTok{ X) }\SpecialCharTok{\%*\%} \FunctionTok{t}\NormalTok{(X)}
\NormalTok{  fit }\OtherTok{\textless{}{-}}\NormalTok{ X }\SpecialCharTok{\%*\%} \FunctionTok{solve}\NormalTok{(}\FunctionTok{t}\NormalTok{(X) }\SpecialCharTok{\%*\%}\NormalTok{ X, }\FunctionTok{t}\NormalTok{(X) }\SpecialCharTok{\%*\%}\NormalTok{ y)}
\NormalTok{  e }\OtherTok{\textless{}{-}}\NormalTok{ y }\SpecialCharTok{{-}}\NormalTok{ fit}
\NormalTok{  loo\_resid }\OtherTok{\textless{}{-}}\NormalTok{ e }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{diag}\NormalTok{(hat))}
  \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(loo\_resid}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{\}}

\NormalTok{cands }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
  \StringTok{\textasciigrave{}}\AttributeTok{tar}\StringTok{\textasciigrave{}}                \OtherTok{=}\NormalTok{ CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tar,}
  \StringTok{\textasciigrave{}}\AttributeTok{nico}\StringTok{\textasciigrave{}}               \OtherTok{=}\NormalTok{ CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nico,}
  \StringTok{\textasciigrave{}}\AttributeTok{weight}\StringTok{\textasciigrave{}}             \OtherTok{=}\NormalTok{ CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ weight,}
  \StringTok{\textasciigrave{}}\AttributeTok{tar+nico}\StringTok{\textasciigrave{}}           \OtherTok{=}\NormalTok{ CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tar }\SpecialCharTok{+}\NormalTok{ nico,}
  \StringTok{\textasciigrave{}}\AttributeTok{tar+weight}\StringTok{\textasciigrave{}}         \OtherTok{=}\NormalTok{ CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tar }\SpecialCharTok{+}\NormalTok{ weight,}
  \StringTok{\textasciigrave{}}\AttributeTok{nico+weight}\StringTok{\textasciigrave{}}        \OtherTok{=}\NormalTok{ CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nico }\SpecialCharTok{+}\NormalTok{ weight,}
  \StringTok{\textasciigrave{}}\AttributeTok{tar+nico+weight}\StringTok{\textasciigrave{}}    \OtherTok{=}\NormalTok{ CO }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tar }\SpecialCharTok{+}\NormalTok{ nico }\SpecialCharTok{+}\NormalTok{ weight}
\NormalTok{)}

\NormalTok{eval\_models }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(dat) \{}
  \FunctionTok{do.call}\NormalTok{(rbind, }\FunctionTok{lapply}\NormalTok{(}\FunctionTok{names}\NormalTok{(cands), }\ControlFlowTok{function}\NormalTok{(nm) \{}
\NormalTok{    fm }\OtherTok{\textless{}{-}}\NormalTok{ cands[[nm]]}
\NormalTok{    fit }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(fm, }\AttributeTok{data =}\NormalTok{ dat)}
    \FunctionTok{data.frame}\NormalTok{(}
      \AttributeTok{model =}\NormalTok{ nm,}
      \AttributeTok{adj\_R2 =} \FunctionTok{summary}\NormalTok{(fit)}\SpecialCharTok{$}\NormalTok{adj.r.squared,}
      \AttributeTok{RMSEP\_LOOCV =} \FunctionTok{loocv\_rmsep}\NormalTok{(fm, dat),}
      \AttributeTok{df =} \FunctionTok{length}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit))}
\NormalTok{    )}
\NormalTok{  \}))}
\NormalTok{\}}

\NormalTok{tab\_full   }\OtherTok{\textless{}{-}} \FunctionTok{eval\_models}\NormalTok{(cig)}
\NormalTok{tab\_reduced}\OtherTok{\textless{}{-}} \FunctionTok{eval\_models}\NormalTok{(cig\_red)  }\CommentTok{\# utan den flaggade observationen identifierad i (e)}

\NormalTok{tab\_full[}\FunctionTok{order}\NormalTok{(tab\_full}\SpecialCharTok{$}\NormalTok{RMSEP\_LOOCV), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             model    adj_R2 RMSEP_LOOCV df
## 1             tar 0.9131598    1.703965  2
## 4        tar+nico 0.9111836    1.767653  3
## 5      tar+weight 0.9092633    1.820918  3
## 7 tar+nico+weight 0.9069593    1.891851  4
## 2            nico 0.8511775    2.158176  2
## 6     nico+weight 0.8444138    2.273199  3
## 3          weight 0.1811389    4.612821  2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tab\_reduced[}\FunctionTok{order}\NormalTok{(tab\_reduced}\SpecialCharTok{$}\NormalTok{RMSEP\_LOOCV), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             model    adj_R2 RMSEP_LOOCV df
## 1             tar 0.9304375    1.155383  2
## 4        tar+nico 0.9272585    1.212252  3
## 5      tar+weight 0.9286920    1.243623  3
## 7 tar+nico+weight 0.9252216    1.312462  4
## 2            nico 0.8597440    1.619577  2
## 6     nico+weight 0.8553717    1.701064  3
## 3          weight 0.0551404    4.435733  2
\end{verbatim}

\textbf{Tolkning 2(f) -- modellval:}

\begin{itemize}
\tightlist
\item
  \textbf{Bästa prediktor:} \emph{Tjära}. Den ger lägst LOOCV-RMSEP och
  högst/lika högt justerat \(R^2\) både med och utan den tvivelaktiga
  observationen.
\item
  \textbf{Övriga:} \emph{Nikotin} förklarar CO väl ensam men tillför
  nästan inget utöver tjära (kollinearitet). \emph{Vikt} är svag.
\item
  \textbf{Rekommenderad modell för prediktion:} \textbf{CO
  \textasciitilde{} tar} (enkel modell). Utan outlieren förbättras RMSEP
  ytterligare (≈1.16 vs ≈1.70) och adj.\(R^2\) ökar (≈0.93). Modellen är
  bäst, enklast och mest stabil.
\end{itemize}

\end{document}
